title: schaefer-dev
url: "https://schaefer-dev.de"
baseurl: "https://schaefer-dev.de"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-131584544-1

footer: yes
footer_url: "https://github.com/schaefer-dev"
footer_text: "Visit my GitHub"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Projects"
   link: "projects"
 - name: "Courses"
   link: "courses"
 - name: "Skills"
   link: "skills"
 - name: "CV"
   link: "cv"
 - name: "Contact"
   link: "contact"
