title: schaefer-dev
url: "https://schaefer-dev.de"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/schaefer-dev"
footer_text: "Page design by Daniel Schaefer"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "index"
 - name: "Projects"
   link: "projects"
 - name: "Skills"
 - name: "Skills"
   link: "skills"
 - name: "CV"
   link: "cv"
 - name: "Contact"
   link: "contact"
