title: schaefer-dev
author: "Daniel Schäfer"
url: "https://schaefer-dev.de"
newbaseurl: "https://schaefer-dev.de"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-131584544-1

footer: yes
footer_url: "https://github.com/schaefer-dev"
footer_text: "Visit my GitHub"

plugins:
   - jekyll-redirect-from

whitelist:
   - jekyll-redirect-from

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Projects"
   link: "projects"
 - name: "Courses"
   link: "courses"
 - name: "Skills"
   link: "skills"
 - name: "CV"
   link: "cv"
 - name: "Contact"
   link: "contact"
